remote_theme: JustGoodThemes/Scriptor-Jekyll-Theme

lang: pl-PL

title: Travel Blog

author: Weroniczka

description: Blog about travelling

baseurl: /travel-blog

navigation:
  - text: Blog
    url: /travel-blog/
  - text: O nas
    url: /travel-blog/about.html
  - text: Tagi
    url: /travel-blog/tags/

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'
