remote_theme: JustGoodThemes/Scriptor-Jekyll-Theme

lang: pl-PL

title: Travel Blog

author: Weroniczka

description: Blog about travelling

navigation:
  - text: Blog
    url: /travel-blog/
  - text: O nas
    url: /travel-blog/about/
