remote_theme: JustGoodThemes/Scriptor-Jekyll-Theme

lang: pl-PL

title: Travel Blog

author: Weroniczka

description: Blog about travelling

baseurl: /travel-blog/
url: https://przemolec.github.io

navigation:
  - text: Blog
    url: /
  - text: O nas
    url: /about/
